export const productLongDescriptions = {
  en: {
    "Amazon Re-Pricing & Market Pricing Tracking": [
      "SITUATION",
      "Fragmented Excel pricing separated market movement from SKU economics.",
      "TASK",
      "Track market prices and win the Buy Box without crossing the commercial floor.",
      "ACTION",
      "Matched PIM and retailer SKUs; combined MSRP, competitors, stock, seller and fulfillment signals with margin guardrails.",
      "UNIT ECONOMICS GUARDRAIL",
      "Realized price − COGS − marketplace and fulfillment − variable media and returns = contribution margin.",
      "Pricing actions advance only when the margin floor is protected; the P&L reads AOV, Buy Box, margin, net profit and OPEX together.",
      "RESULT",
      "Pricing: +11% AOV and +12pp Buy Box.",
      "Related Amazon model: +19% net profit, +8pp margin and −10pp OPEX.",
    ],
  },
  de: {
    "Amazon Re-Pricing & Market Pricing Tracking": [
      "SITUATION",
      "Fragmentierte Excel-Preisgestaltung trennte Marktbewegungen von der SKU-Ökonomie.",
      "TASK",
      "Marktpreise verfolgen und die Buy Box gewinnen, ohne die kommerzielle Untergrenze zu unterschreiten.",
      "ACTION",
      "PIM- und Händler-SKUs abgeglichen und UVP-, Wettbewerber-, Bestands-, Seller- und Fulfillment-Signale mit Margen-Guardrails kombiniert.",
      "UNIT-ECONOMICS-GUARDRAIL",
      "Realisierter Preis − COGS − Marketplace und Fulfillment − variable Media- und Retourenkosten = Deckungsbeitrag.",
      "Pricing-Aktionen werden nur ausgeführt, wenn die Margenuntergrenze geschützt ist; im P&L werden AOV, Buy Box, Marge, Nettogewinn und OPEX gemeinsam betrachtet.",
      "RESULT",
      "Pricing: +11 % AOV und +12 pp Buy Box.",
      "Verbundenes Amazon-Modell: +19 % Nettogewinn, +8 pp Marge und −10 pp OPEX.",
    ],
  },
  tr: {
    "Amazon Re-Pricing & Market Pricing Tracking": [
      "SITUATION",
      "Parçalı Excel fiyatlaması, pazar hareketini SKU ekonomisinden ayırıyordu.",
      "TASK",
      "Ticari alt sınırı aşmadan pazar fiyatlarını takip etmek ve Buy Box'ı kazanmak.",
      "ACTION",
      "PIM ve retailer SKU'ları eşleştirildi; MSRP, rakip, stok, seller ve fulfillment sinyalleri marj guardrail'leriyle birleştirildi.",
      "UNIT ECONOMICS GUARDRAIL",
      "Gerçekleşen fiyat − COGS − marketplace ve fulfillment − değişken medya ve iadeler = katkı marjı.",
      "Fiyatlama aksiyonları yalnızca marj alt sınırı korunduğunda ilerler; P&L, AOV, Buy Box, marj, net kâr ve OPEX'i birlikte okur.",
      "RESULT",
      "Fiyatlama: +%11 AOV ve +12pp Buy Box.",
      "İlgili Amazon modeli: +%19 net kâr, +8pp marj ve −10pp OPEX.",
    ],
  },
} as const;
